### PR TITLE
Compile and test bundler dependency against jammy

### PR DESCRIPTION
**Pull request by sophiewigmore**
This PR updates compilation to run on a Jammy-based image, since we can easily install a newer version of Ruby which is compatible with newer Bundler versions. The same dependency can be used on both Jammy and Bionic stacks, and has been tested against the Ruby language family buildpack integration tests.

This option has some drawbacks:
- We can no longer test against the compiled dependency on the Bionic stack, because we run into the same failures as we saw with compilation related to incompatible Ruby versions.
- We can't use the Jammy stack image directly for compilation, because we are removing Ruby (per https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0008-jammy-full-remove-ruby.md), and will still need to install it.

## Alternatives
A. Find a way to install Ruby 2.6+ on Bionic so that we can continue to compile/test on Bionic
B. Don't support bundler 2.4+ on Bionic

## Background
We have been seeing [failures to compile](https://github.com/paketo-buildpacks/bundler/issues/449) Bundler 2.4.* due to incompatibilities with Ruby 2.5 and below. Currently, we compile bundle on a bionic-based image, which now fails because Ubuntu only provides Ruby 2.5.

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@robdimsdale in terms of testing the dependency, the language family tests all pass on both Jammy and Bionic builders when using the Jammy-compiled dependency.

I also successfully built the Rails app we had previously seen graceful stack error failures related to bundler/openssl in, which gives me hope that this is a viable solution

**Review by ryanmoran — APPROVED** [review]

**Comment by robdimsdale** [comment]
@sophiewigmore sounds good - thanks for taking the extra step of validating rails apps with SSL work as expected.

I think this is good enough to try now.

Instead of merging this PR, I'd suggest we remove the bionic dependencies from `buildpack.toml`, add that change to this branch as well, and manually run the action from this branch. That will force a recompilation of the bionic dependencies and open a PR, so we'll get to see the integration tests running on the bionic stack in that PR. If that surfaces any issues, we will discover them before merging the compilation changes in this PR directly to main.

Assuming that PR passes, this one can be closed. If there are issues, we'll fix them on this branch and re-run the action from this branch.

Does that process make sense?

**Comment by sophiewigmore** [comment]
@robdimsdale sounds great, I can do that!

**Comment by sophiewigmore** [comment]
@robdimsdale https://github.com/paketo-buildpacks/bundler/pull/452

**Comment by sophiewigmore** [comment]
Closing in favour of #456

**Pull request closed without merging**
